module: KituraCSRF
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-CSRF/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Kitura-CSRF.xcodeproj, -target, KituraCSRF, LIBRARY_SEARCH_PATHS=.build/debug]
